signature ::= (name '=')? type ';'
name ::= [a-z] (('.')? [a-zA-Z0-9_])*
type ::= (
    function
    | 'Generic'
    | 'List' ('(' type ')')?
    | 'Object'
    | 'Int'
    | 'Float'
    | 'String'
    | custom-type
)
function ::= (
    'Fn' ('('
        ( (name ':')? type (',' (name ':')? type)* (',')? )?
    ')')?
    ('->' type)?
    ('=' (type | ECMAScriptExpression))?
)
custom-type ::= (name '.')? [A-Z] [A-Za-z0-9]*
